table 'Input data Table 3'
	lineageTag: 2246f4a1-aa5b-4ec9-b24e-1b64dc72a9d2

	column 'Responded PCA ID'
		dataType: int64
		formatString: 0
		lineageTag: 73077df7-bd2e-49b1-9421-335e2870266f
		summarizeBy: count
		sourceColumn: Responded PCA ID

		annotation SummarizationSetBy = Automatic

	column 'Responded PCA Name'
		dataType: string
		lineageTag: 3c5547e4-da8b-4e97-aed7-7e9a38bca6e4
		summarizeBy: none
		sourceColumn: Responded PCA Name

		annotation SummarizationSetBy = Automatic

	column 'Reporting Year'
		dataType: int64
		formatString: 0
		lineageTag: 9e95b054-05f5-4b7b-9770-ca62e3de24a5
		summarizeBy: sum
		sourceColumn: Reporting Year

		annotation SummarizationSetBy = Automatic

	column 'Connecting PCA'
		dataType: string
		lineageTag: 2f71e7fd-8d6c-446a-baa5-cb0f261d845e
		summarizeBy: none
		sourceColumn: Connecting PCA

		annotation SummarizationSetBy = Automatic

	column 'Connecting PCA ID'
		dataType: string
		lineageTag: 92621086-228a-43b8-8601-d43eea8b7374
		summarizeBy: none
		sourceColumn: Connecting PCA ID

		annotation SummarizationSetBy = Automatic

	column 'Electricity Generation (MWh)'
		dataType: double
		formatString: 0.000
		lineageTag: 592c5b2d-e938-4890-b3d1-395ba7c945cb
		summarizeBy: sum
		sourceColumn: Electricity Generation (MWh)

		annotation SummarizationSetBy = Automatic

	column 'Import ratio'
		dataType: double
		lineageTag: 09391713-e8aa-4d0c-a34e-98a247fed902
		summarizeBy: sum
		sourceColumn: Import ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Water intensity (m3/MWH)'
		dataType: double
		formatString: 0.000000000000000
		lineageTag: 2582f49e-b6da-427b-934e-b5a564a40152
		summarizeBy: sum
		sourceColumn: Water intensity (m3/MWH)

		annotation SummarizationSetBy = Automatic

	partition 'Input data Table 3' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\arnav\Downloads\Datasetsfor Bankruptcy\Clean Datasets\SI_XLS\Input data Table 3.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Responded PCA ID", Int64.Type}, {"Responded PCA Name", type text}, {"Reporting Year", Int64.Type}, {"Connecting PCA", type text}, {"Connecting PCA ID", type text}, {"Electricity Generation (MWh)", type number}, {"Import ratio", type number}, {"Water intensity (m3/MWH)", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

